### ISSUE TITLE
Fix Unit tests

### ISSUE THREAD

**Issue by Unknown6656** [Unknown6656/MCPU#24]
Fix the following unit tests:

- [x] Compiler Test № 14 (PR #59)
- [x] Compiler Test № 16 (PR #59)
- [x] Compiler Test № 23 (PR #46)
- [x] Lexer Test № 2 (PR #52)
- [x] Lexer Test № 4 (PR #57)
- [x] Lexer Test № 5 (PR #57)
- [x] Lexer Test № 6 (PR #57)
- [x] Lexer Test № 9 (PR #58)
- [x] Lexer Test № 10 (PR #58)
- [x] Lexer Test № 11 (PR #58)
- [x] Lexer Test № 12 (PR #58)
- [x] Processor Test № 5 (PR #51)
- [x] Processor Test № 7 (PR #40)
- [x] Processor Test № 8 (PR #40, #51)
- [x] Processor Test № 9 (PR #51)
- [x] Processor Test № 14 (PR #51)
- [x] Processor Test № 18 (PR #51)
- [x] Processor Test № 23 (PR #51)

**Comment by Unknown6656** [comment]
~ Resolved
