### ISSUE TITLE
Fix Unit Tests

### ISSUE THREAD

**Issue by Unknown6656** [Unknown6656/MCPU#60]
Fix the following unit tests:

- [x] Analyzer Test № 1 (PR #62)
- [x] Analyzer Test № 12 (related to #61, PR #70)
- [x] Analyzer Test № 13 (related to #61, PR #70)
- [x] Analyzer Test № 14 (related to #61, PR #70)
- [x] Analyzer Test № 22 (related to #61, PR #70)
- [x] Analyzer Test № 35 (related to #61, PR #70)
- [x] Analyzer Test № 36 (related to #61, PR #70)
- [x] Analyzer Test № 37 (related to #61, PR #70)
